#
# Makefile for EvilEngine/CoreBugReport
#
LIB=CoreBugReport

CPP_SOURCES := \
	Common/BugReport.cpp \
	Client/BugReportClient.cpp \
	Server/BugReportServer.cpp

include $(EVILENGINEPATH)/MakefileRule.Files.Include
