#
# Makefile for EvilEngine/CoreEngine
#
LIB=CoreEngine

CPP_SOURCES := \
	CoreBaseObject/CoreBaseObject.cpp \
	CoreEngine/CoreEngine.cpp \
	CoreResourceManager/CoreResourceManager_Common.cpp \
	CoreResourceManager/CoreResourceManager_Linux.cpp \
	CoreResourceManager/Resource.cpp \
	CoreEventTimer/EventTimer.cpp \
	CoreEventTimer/EventTimerManager.cpp \
	CoreEffectSystem/EffectPackage.cpp \
	CoreInput/CoreInputManager.cpp \
	CoreInput/Keyboard_Common.cpp \
	CoreInput/Keyboard_Linux.cpp
	
include $(EVILENGINEPATH)/MakefileRule.Files.Include
