#
# Makefile for EvilEngine/CoreLib
#
LIB=CoreIO
DEPENDLIBS=CoreLib

CPP_SOURCES := \
	ConfigReader/ConfigReader.cpp \
	File/IOFile.cpp \
	Logger/Logger.cpp \
	UserConfig/UserConfig_Common.cpp \
	UserConfig/UserConfig_Linux.cpp
	
include $(EVILENGINEPATH)/MakefileRule.Files.Include
