#
# Makefile for EvilGameEngine/CoreGameLogin
#
LIB=CoreGameLogin
#DEPENDLIBS=CoreLib

CPP_SOURCES := \
	Account/Account.cpp \
	Account/AccountManager.cpp \
	LoginModule/CoreGameBaseLoginModule.cpp \
	LoginModule/CoreGameServerLoginModule.cpp \
	Network/BaseAuthentcatedNetworkPacket.cpp \
	Network/BaseLoginModuleNetworkPacket.cpp \
	NetworkPackets/ClientAccountNetworkPackets/ClientAccountCreatedNetworkPacket.cpp \
	NetworkPackets/ClientAccountNetworkPackets/ClientAccountErrorNetworkPacket.cpp \
	NetworkPackets/ClientAccountNetworkPackets/ClientAccountLoggedOnNetworkPacket.cpp \
	NetworkPackets/ClientAccountNetworkPackets/ClientAccountLoggedOffNetworkPacket.cpp \
	NetworkPackets/ServerAccountNetworkPackets/CreateServerAccountNetworkPacket.cpp \
	NetworkPackets/ServerAccountNetworkPackets/LoginServerAccountNetworkPacket.cpp \
	NetworkPackets/ServerAccountNetworkPackets/LoginGMNetworkPacket.cpp \
	NetworkPackets/ServerAccountNetworkPackets/SwitchLoggedInAccountNetworkPacket.cpp \
	NetworkPackets/ServerAccountNetworkPackets/UpdatedAccountFlagsNetworkPacket.cpp \
	NetworkPackets/ItemShopPackets/PurchaseItemFromAmazonNetworkPacket.cpp \
	NetworkPackets/ItemShopPackets/PurchaseItemFromAppleNetworkPacket.cpp \
	NetworkPackets/ItemShopPackets/PurchaseItemFromDarkfactorNetworkPacket.cpp

include $(EVILENGINEPATH)/MakefileRule.Files.Include
