#
# Makefile for EvilGameEngine/CoreBoardGame
#
LIB=CoreBoardGame
#DEPENDLIBS=CoreLib

CPP_SOURCES := \
	GameEngine/BoardGameEngine.cpp \
	GameEngine/CoreBaseRenderObject.cpp \
	GameLogic/Game/BoardGame.cpp \
	GameLogic/Game/BoardGameServer.cpp \
	GameLogic/GameObject/GameObject.cpp \
	GameLogic/GameObject/Item.cpp \
	GameLogic/Character/Character.cpp \
	GameLogic/Player/Player.cpp \
	GameLogic/XPTable/XPTable.cpp \
	Network/GameNetworkPackets/BaseGameNetworkPacket.cpp \
	Network/GameNetworkPackets/DeleteGameNetworkPacket.cpp \
	Network/GameNetworkPackets/NewGameNetworkPacket.cpp \
	Network/GameNetworkPackets/CreateGameWithPlayerNetworkPacket.cpp \
	Network/GameNetworkPackets/CreateGameWithRandomPlayerNetworkPacket.cpp \
	Network/GameNetworkPackets/SearchForPlayerWithNickNetworkPacket.cpp \
	Network/GameNetworkPackets/GameListNetworkPacket.cpp \
	Network/PlayfieldNetworkPackets/LoadPlayfieldNetworkPacket.cpp \
	Network/PlayfieldNetworkPackets/SavePlayfieldNetworkPacket.cpp \
	Network/PlayfieldNetworkPackets/DeletePlayfieldNetworkPacket.cpp \
	Network/PlayfieldNetworkPackets/PlayfieldListNetworkPacket.cpp \
	Playfield/Tiles/BaseTile.cpp \
	Playfield/Tiles/HexTile.cpp \
	Playfield/Tiles/QuadTile.cpp \
	Playfield/PlayfieldInfo.cpp \
	Playfield/PlayfieldInfoManager.cpp \
	Playfield/GridTilePlayfield.cpp \
	Playfield/Pathfinding/GridTilePathfinding.cpp 
	
include $(EVILENGINEPATH)/MakefileRule.Files.Include
