#
# Makefile for EvilEngine/CoreLib
#
LIB=CoreNetwork
DEPENDLIBS=CoreLib

CPP_SOURCES := \
	Client/NetworkClient.cpp \
	Common/NetworkBase.cpp \
	Common/NetworkConnection.cpp \
	Common/NetworkReactor.cpp \
	Server/NetworkServer.cpp \
        Engine/CoreNetworkEngine.cpp \
	EmailConnection/EmailNetworkClient.cpp \
	EmailConnection/EmailNetworkConnection.cpp \
	HttpNetworkClient/HttpNetworkClient.cpp \
	ZLibCompression/ZlibCompression.cpp \
	SSLNetworkClient/SSLNetworkClient.cpp

include $(EVILENGINEPATH)/MakefileRule.Files.Include
