
FOLDERS=CorePatcherModule CoreBoardGame CoreGameLogin CoreGameEngine

all: debug release

debug:
	make folder_debug

release:
	make folder_release

clean:
	make folder_clean

include $(EVILENGINEPATH)/MakefileRule.Folder.Include

