# Use .Net Core 3.1 image
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env
WORKDIR /app

# Add nuget repository
#COPY ./NuGet/DarkFactor.Common.Lib.*.nupkg ./NuGet/
#RUN dotnet nuget add source /app/NuGet --name DarkFactor

# Flush all nuget repos
#RUN dotnet nuget locals all -c

# Copy files
COPY ./ ./

# Copy nuget file
COPY ./NuGet_Docker.config ./NuGet.config

# Restore and build web
RUN dotnet restore BotWebServer.csproj
RUN dotnet publish BotWebServer.csproj -c Release -o out

# Create self signed sertificate
RUN dotnet dev-certs https -ep /app/out/certificate.pfx -p smurfepoliz
#RUN dotnet dev-certs https --trust

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build-env /app/out .
ENTRYPOINT ["dotnet", "BotWebServer.dll"]

EXPOSE 5000:80
