#
# Makefile for EvilEngine/CoreGameEngine
#
LIB=CoreGameEngine

CPP_SOURCES := \
	CoreEffectSystem/CoreEffectSystem.cpp \
	CoreScreenModule/CoreScreenModule.cpp \
        CoreGameNetwork/Packets/BaseNetworkPacket.cpp \
        CoreGameNetwork/Packets/ReceiveServerVersionNetworkPacket.cpp \
        CoreGameNetwork/Packets/RequestServerVersionNetworkPacket.cpp \
        CoreGameNetwork/Packets/ServerErrorNetworkPacket.cpp \
 	CoreGameEngine.cpp \
	CoreGameEngineModule.cpp
	
include $(EVILENGINEPATH)/MakefileRule.Files.Include
