#
# Makefile for EvilEngine/CoreLib
#
LIB=CoreLib

CPP_SOURCES := \
        Assert/DFAssert_Common.cpp \
        Assert/DFAssert_Linux.cpp \
        Assert/DFAssert_OSX.cpp \
        Assert/DFCallstack.cpp \
        BasicTypes/String/CoreString.cpp \
        BasicTypes/String/StringId.cpp \
        BasicTypes/String/StringList.cpp \
        BasicTypes/Bundle/Bundle.cpp \
        BasicTypes/Mutex/Mutex.cpp \
        BasicTypes/Mutex/ScopedMutex.cpp \
        BasicTypes/BinaryStream/BinaryStream.cpp \
	BasicTypes/Variant/Variant.cpp \
	BasicTypes/Variant/VariantTree.cpp \
	Crypto/ElfHash.cpp \
        CRC32/crc32.cpp \
        Md5/md5.cpp \
        Thread/Thread.cpp \
	Utils/CoreUtils.cpp \
	Utils/Base64Util.cpp \
	CoreMath/Color.cpp \
	CoreMath/Matrix.cpp \
	CoreMath/Quaternion.cpp \
	CoreMath/Vector2.cpp \
	CoreMath/Vector3.cpp \
	Signal/SignalBase.cpp \
	Signal/SignalTarget.cpp \
	Signal/SlotBase.cpp

include ../MakefileRule.Files.Include
