#
# Makefile to build the Valyrian Adventures Linux Server
#

export LD_LIBS = ProjectGameEngine CorePatcherModule CoreGameLogin CoreBoardGame CoreGameEngine CoreBugReport CoreEngine CoreDatabase CoreNetwork CoreIO CoreLib

include $(EVILENGINEPATH)/Makefile.Include.Settings
include $(EVILENGINEPATH)/Makefile.Include.Linker
include $(EVILENGINEPATH)/MakefileRule.Folder.Include

